version: '3'
services:
  mongodb:
    image: "mongo"
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    restart: always

  api:
    image: "chernandez05/backendt2"
    container_name: api_container
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: "chernandez05/frontendt2"
    container_name: frontend_container
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - api
    links:
      - api
volumes:
  mongodbdata: 